services:
  web:
    build: .
    container_name: flask-web 
    ports:
    - "5000:5000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  
  
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskusr
      MYSQL_PASSWORD: 1357901111
    volumes:
      - ./app/utils:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 3

volumes:
  mysql_data: