name: Deploy Flask + MySQL to AWS EB

on:
    push:
        branches: [ "main"]
            
env:
    AWS_REGION: ap-southeast-1

permissions:
    id-token: write
    contents: read

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Set up Python 
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'
        # 其它step: install pkg, running test 

    # the second task 
    compose:
      runs-on: ubuntu-latest
      needs: build # 依赖于 build 
      steps:
        - name: Set up Docker Compose
          uses: docker/setup-compose-action@v1
        
        - name: Build and Test
          run: |
            docker compose up --build -d
            docker ps
            sleep 30
            curl -f http://localhost:5000 || exit 1
            docker-compose down

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: compose
        environment: production

        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Install EB CLI
          run: pip install awsebcli

        - name: Configure AWS credentials using OIDC
          uses: aws-actions/configure-aws-credentials@v4
          with: 
            role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
            aws-region: ${{ env.AWS_REGION }}

